name: Server CI

on:
    push:
        paths-ignore:
            - 'website/**'
            - '.github/workflows/*.website.yml'
            - '**/*.md'

defaults:
    run:
        working-directory: server

jobs:
    build:
        name: Node ${{ matrix.node-version }}
        runs-on: ubuntu-latest
        timeout-minutes: 1

        strategy:
            matrix:
                node-version: [20.x, 22.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 9

            - name: Setup Node ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Typecheck
              run: pnpm typecheck

            - name: Lint
              run: pnpm lint

            - name: Test
              run: pnpm coverage

            - name: Upload test coverage
              uses: codecov/codecov-action@v4.3.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN  }}
                  flags: server

            - name: Build
              run: pnpm build

            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build (${{ matrix.node-version }})
                  path: server/build
